services:
  db:
    image: "postgres:16.1-alpine3.18"
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:z,ro
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_ADMIN_PASSWORD:-admin}"
      POSTGRES_USER: "${POSTGRES_ADMIN_USER:-postgres}"
    ports:
      - "5432:5432"
    env_file:
      - .env

  pgadmin:
    image: dpage/pgadmin4:8.12
    environment:
      PGADMIN_DEFAULT_EMAIL: "${PGADMIN_DEFAULT_EMAIL:-admin@local}"
      PGADMIN_DEFAULT_PASSWORD: "${PGADMIN_DEFAULT_PASSWORD:-admin}"
    ports:
      - "5050:80"
    depends_on:
      - db
    env_file:
      - .env

volumes:
  db-data:
  datastore:
